<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto

namespace GPBMetadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xC3\x01\x0A\x0Dservice.proto\x12\x05proto\"\x1A\x0A\x0CEventRequest\x12\x0A\x0A\x02id\x18\x01 \x01(\x03\"9\x0A\x0DEventResponse\x12\x0A\x0A\x02id\x18\x01 \x01(\x03\x12\x0C\x0A\x04name\x18\x02 \x01(\x09\x12\x0E\x0A\x06active\x18\x03 \x01(\x082C\x0A\x0AAddService\x125\x0A\x08GetEvent\x12\x13.proto.EventRequest\x1A\x14.proto.EventResponseB\x07Z\x05./;pbb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

